version: '3.9'

services:

  db:
    container_name: postgres
    image: postgres

    environment:
      POSTGRES_USER: zefferx
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - ./database:/data/postgres
    ports:
        - "5332:5432"

    restart: unless-stopped
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"




